### ISSUE TITLE
Analysis part 1 feedback

### ISSUE THREAD

**Issue by ugurdogrusoz** [Albocoder/CS319-Group22#3]
Nice overall some minor comments I have in the attached document.
[22.analysis.1.pdf](https://github.com/Albocoder/CS319-Group22/files/543831/22.analysis.1.pdf)

**Comment by Albocoder** [comment]
@ugurdogrusoz 
Firstly, I thank you for the feedback. I would want to clarify something about the voting system. The user is supposed to use such system just to help him play the game. The user casts the vote to start game, end game or even kick a player so it plays a support role rather than primary. 
In your opinion, do we still need to add that as use case or many use cases or just leave it like in our design?
Many thanks in advance

Erin Avllazagaj

**Comment by ugurdogrusoz** [comment]
I think so since this is a feature that might separate your version of the game from others.
